POST http://localhost:3000/api/estudiantes
Content-Type: application/json

{
  "nombre": "Pocholo",
  "curso": "Bim Bada Boom"
}

###

POST http://localhost:3000/api/profesores
Content-Type: application/json

{
  "nombre": "Don Quijote",
  "asignatura": "Lectura Medieval"
}